// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/GustavoStingelin/nix-machinary/zwm/internal/git"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBranchGit creates a new instance of MockBranchGit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBranchGit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBranchGit {
	mock := &MockBranchGit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBranchGit is an autogenerated mock type for the BranchGit type
type MockBranchGit struct {
	mock.Mock
}

type MockBranchGit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBranchGit) EXPECT() *MockBranchGit_Expecter {
	return &MockBranchGit_Expecter{mock: &_m.Mock}
}

// AddExistingWorktree provides a mock function for the type MockBranchGit
func (_mock *MockBranchGit) AddExistingWorktree(context1 context.Context, directory git.Directory, worktreePath git.WorktreePath, branch git.Branch) error {
	ret := _mock.Called(context1, directory, worktreePath, branch)

	if len(ret) == 0 {
		panic("no return value specified for AddExistingWorktree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.WorktreePath, git.Branch) error); ok {
		r0 = returnFunc(context1, directory, worktreePath, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchGit_AddExistingWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddExistingWorktree'
type MockBranchGit_AddExistingWorktree_Call struct {
	*mock.Call
}

// AddExistingWorktree is a helper method to define mock.On call
//   - context1 context.Context
//   - directory git.Directory
//   - worktreePath git.WorktreePath
//   - branch git.Branch
func (_e *MockBranchGit_Expecter) AddExistingWorktree(context1 interface{}, directory interface{}, worktreePath interface{}, branch interface{}) *MockBranchGit_AddExistingWorktree_Call {
	return &MockBranchGit_AddExistingWorktree_Call{Call: _e.mock.On("AddExistingWorktree", context1, directory, worktreePath, branch)}
}

func (_c *MockBranchGit_AddExistingWorktree_Call) Run(run func(context1 context.Context, directory git.Directory, worktreePath git.WorktreePath, branch git.Branch)) *MockBranchGit_AddExistingWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 git.Directory
		if args[1] != nil {
			arg1 = args[1].(git.Directory)
		}
		var arg2 git.WorktreePath
		if args[2] != nil {
			arg2 = args[2].(git.WorktreePath)
		}
		var arg3 git.Branch
		if args[3] != nil {
			arg3 = args[3].(git.Branch)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBranchGit_AddExistingWorktree_Call) Return(err error) *MockBranchGit_AddExistingWorktree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchGit_AddExistingWorktree_Call) RunAndReturn(run func(context1 context.Context, directory git.Directory, worktreePath git.WorktreePath, branch git.Branch) error) *MockBranchGit_AddExistingWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// AddNewWorktree provides a mock function for the type MockBranchGit
func (_mock *MockBranchGit) AddNewWorktree(context1 context.Context, directory git.Directory, branch git.Branch, worktreePath git.WorktreePath, commit git.Commit) error {
	ret := _mock.Called(context1, directory, branch, worktreePath, commit)

	if len(ret) == 0 {
		panic("no return value specified for AddNewWorktree")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.Branch, git.WorktreePath, git.Commit) error); ok {
		r0 = returnFunc(context1, directory, branch, worktreePath, commit)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchGit_AddNewWorktree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNewWorktree'
type MockBranchGit_AddNewWorktree_Call struct {
	*mock.Call
}

// AddNewWorktree is a helper method to define mock.On call
//   - context1 context.Context
//   - directory git.Directory
//   - branch git.Branch
//   - worktreePath git.WorktreePath
//   - commit git.Commit
func (_e *MockBranchGit_Expecter) AddNewWorktree(context1 interface{}, directory interface{}, branch interface{}, worktreePath interface{}, commit interface{}) *MockBranchGit_AddNewWorktree_Call {
	return &MockBranchGit_AddNewWorktree_Call{Call: _e.mock.On("AddNewWorktree", context1, directory, branch, worktreePath, commit)}
}

func (_c *MockBranchGit_AddNewWorktree_Call) Run(run func(context1 context.Context, directory git.Directory, branch git.Branch, worktreePath git.WorktreePath, commit git.Commit)) *MockBranchGit_AddNewWorktree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 git.Directory
		if args[1] != nil {
			arg1 = args[1].(git.Directory)
		}
		var arg2 git.Branch
		if args[2] != nil {
			arg2 = args[2].(git.Branch)
		}
		var arg3 git.WorktreePath
		if args[3] != nil {
			arg3 = args[3].(git.WorktreePath)
		}
		var arg4 git.Commit
		if args[4] != nil {
			arg4 = args[4].(git.Commit)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockBranchGit_AddNewWorktree_Call) Return(err error) *MockBranchGit_AddNewWorktree_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchGit_AddNewWorktree_Call) RunAndReturn(run func(context1 context.Context, directory git.Directory, branch git.Branch, worktreePath git.WorktreePath, commit git.Commit) error) *MockBranchGit_AddNewWorktree_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorktrees provides a mock function for the type MockBranchGit
func (_mock *MockBranchGit) ListWorktrees(context1 context.Context, directory git.Directory) ([]byte, error) {
	ret := _mock.Called(context1, directory)

	if len(ret) == 0 {
		panic("no return value specified for ListWorktrees")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory) ([]byte, error)); ok {
		return returnFunc(context1, directory)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory) []byte); ok {
		r0 = returnFunc(context1, directory)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, git.Directory) error); ok {
		r1 = returnFunc(context1, directory)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBranchGit_ListWorktrees_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorktrees'
type MockBranchGit_ListWorktrees_Call struct {
	*mock.Call
}

// ListWorktrees is a helper method to define mock.On call
//   - context1 context.Context
//   - directory git.Directory
func (_e *MockBranchGit_Expecter) ListWorktrees(context1 interface{}, directory interface{}) *MockBranchGit_ListWorktrees_Call {
	return &MockBranchGit_ListWorktrees_Call{Call: _e.mock.On("ListWorktrees", context1, directory)}
}

func (_c *MockBranchGit_ListWorktrees_Call) Run(run func(context1 context.Context, directory git.Directory)) *MockBranchGit_ListWorktrees_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 git.Directory
		if args[1] != nil {
			arg1 = args[1].(git.Directory)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBranchGit_ListWorktrees_Call) Return(bytes []byte, err error) *MockBranchGit_ListWorktrees_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockBranchGit_ListWorktrees_Call) RunAndReturn(run func(context1 context.Context, directory git.Directory) ([]byte, error)) *MockBranchGit_ListWorktrees_Call {
	_c.Call.Return(run)
	return _c
}

// LocalBranchExists provides a mock function for the type MockBranchGit
func (_mock *MockBranchGit) LocalBranchExists(context1 context.Context, directory git.Directory, branch git.Branch) (bool, error) {
	ret := _mock.Called(context1, directory, branch)

	if len(ret) == 0 {
		panic("no return value specified for LocalBranchExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.Branch) (bool, error)); ok {
		return returnFunc(context1, directory, branch)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.Branch) bool); ok {
		r0 = returnFunc(context1, directory, branch)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, git.Directory, git.Branch) error); ok {
		r1 = returnFunc(context1, directory, branch)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBranchGit_LocalBranchExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalBranchExists'
type MockBranchGit_LocalBranchExists_Call struct {
	*mock.Call
}

// LocalBranchExists is a helper method to define mock.On call
//   - context1 context.Context
//   - directory git.Directory
//   - branch git.Branch
func (_e *MockBranchGit_Expecter) LocalBranchExists(context1 interface{}, directory interface{}, branch interface{}) *MockBranchGit_LocalBranchExists_Call {
	return &MockBranchGit_LocalBranchExists_Call{Call: _e.mock.On("LocalBranchExists", context1, directory, branch)}
}

func (_c *MockBranchGit_LocalBranchExists_Call) Run(run func(context1 context.Context, directory git.Directory, branch git.Branch)) *MockBranchGit_LocalBranchExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 git.Directory
		if args[1] != nil {
			arg1 = args[1].(git.Directory)
		}
		var arg2 git.Branch
		if args[2] != nil {
			arg2 = args[2].(git.Branch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchGit_LocalBranchExists_Call) Return(b bool, err error) *MockBranchGit_LocalBranchExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBranchGit_LocalBranchExists_Call) RunAndReturn(run func(context1 context.Context, directory git.Directory, branch git.Branch) (bool, error)) *MockBranchGit_LocalBranchExists_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveCommit provides a mock function for the type MockBranchGit
func (_mock *MockBranchGit) ResolveCommit(context1 context.Context, directory git.Directory, commitish git.Commitish) (git.Commit, error) {
	ret := _mock.Called(context1, directory, commitish)

	if len(ret) == 0 {
		panic("no return value specified for ResolveCommit")
	}

	var r0 git.Commit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.Commitish) (git.Commit, error)); ok {
		return returnFunc(context1, directory, commitish)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.Commitish) git.Commit); ok {
		r0 = returnFunc(context1, directory, commitish)
	} else {
		r0 = ret.Get(0).(git.Commit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, git.Directory, git.Commitish) error); ok {
		r1 = returnFunc(context1, directory, commitish)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBranchGit_ResolveCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveCommit'
type MockBranchGit_ResolveCommit_Call struct {
	*mock.Call
}

// ResolveCommit is a helper method to define mock.On call
//   - context1 context.Context
//   - directory git.Directory
//   - commitish git.Commitish
func (_e *MockBranchGit_Expecter) ResolveCommit(context1 interface{}, directory interface{}, commitish interface{}) *MockBranchGit_ResolveCommit_Call {
	return &MockBranchGit_ResolveCommit_Call{Call: _e.mock.On("ResolveCommit", context1, directory, commitish)}
}

func (_c *MockBranchGit_ResolveCommit_Call) Run(run func(context1 context.Context, directory git.Directory, commitish git.Commitish)) *MockBranchGit_ResolveCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 git.Directory
		if args[1] != nil {
			arg1 = args[1].(git.Directory)
		}
		var arg2 git.Commitish
		if args[2] != nil {
			arg2 = args[2].(git.Commitish)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchGit_ResolveCommit_Call) Return(commit git.Commit, err error) *MockBranchGit_ResolveCommit_Call {
	_c.Call.Return(commit, err)
	return _c
}

func (_c *MockBranchGit_ResolveCommit_Call) RunAndReturn(run func(context1 context.Context, directory git.Directory, commitish git.Commitish) (git.Commit, error)) *MockBranchGit_ResolveCommit_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateBranch provides a mock function for the type MockBranchGit
func (_mock *MockBranchGit) ValidateBranch(context1 context.Context, directory git.Directory, branch git.Branch) error {
	ret := _mock.Called(context1, directory, branch)

	if len(ret) == 0 {
		panic("no return value specified for ValidateBranch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, git.Directory, git.Branch) error); ok {
		r0 = returnFunc(context1, directory, branch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBranchGit_ValidateBranch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateBranch'
type MockBranchGit_ValidateBranch_Call struct {
	*mock.Call
}

// ValidateBranch is a helper method to define mock.On call
//   - context1 context.Context
//   - directory git.Directory
//   - branch git.Branch
func (_e *MockBranchGit_Expecter) ValidateBranch(context1 interface{}, directory interface{}, branch interface{}) *MockBranchGit_ValidateBranch_Call {
	return &MockBranchGit_ValidateBranch_Call{Call: _e.mock.On("ValidateBranch", context1, directory, branch)}
}

func (_c *MockBranchGit_ValidateBranch_Call) Run(run func(context1 context.Context, directory git.Directory, branch git.Branch)) *MockBranchGit_ValidateBranch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 git.Directory
		if args[1] != nil {
			arg1 = args[1].(git.Directory)
		}
		var arg2 git.Branch
		if args[2] != nil {
			arg2 = args[2].(git.Branch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBranchGit_ValidateBranch_Call) Return(err error) *MockBranchGit_ValidateBranch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBranchGit_ValidateBranch_Call) RunAndReturn(run func(context1 context.Context, directory git.Directory, branch git.Branch) error) *MockBranchGit_ValidateBranch_Call {
	_c.Call.Return(run)
	return _c
}
