// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/GustavoStingelin/nix-machinary/zwm/internal/cli"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockService
func (_mock *MockService) Execute(context1 context.Context, invocation cli.Invocation) (cli.Result, error) {
	ret := _mock.Called(context1, invocation)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 cli.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cli.Invocation) (cli.Result, error)); ok {
		return returnFunc(context1, invocation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cli.Invocation) cli.Result); ok {
		r0 = returnFunc(context1, invocation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cli.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cli.Invocation) error); ok {
		r1 = returnFunc(context1, invocation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - invocation cli.Invocation
func (_e *MockService_Expecter) Execute(context1 interface{}, invocation interface{}) *MockService_Execute_Call {
	return &MockService_Execute_Call{Call: _e.mock.On("Execute", context1, invocation)}
}

func (_c *MockService_Execute_Call) Run(run func(context1 context.Context, invocation cli.Invocation)) *MockService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cli.Invocation
		if args[1] != nil {
			arg1 = args[1].(cli.Invocation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Execute_Call) Return(result cli.Result, err error) *MockService_Execute_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockService_Execute_Call) RunAndReturn(run func(context1 context.Context, invocation cli.Invocation) (cli.Result, error)) *MockService_Execute_Call {
	_c.Call.Return(run)
	return _c
}
