// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/GustavoStingelin/nix-machinary/zwm/internal/zellij"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTabLauncher creates a new instance of MockTabLauncher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTabLauncher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTabLauncher {
	mock := &MockTabLauncher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTabLauncher is an autogenerated mock type for the TabLauncher type
type MockTabLauncher struct {
	mock.Mock
}

type MockTabLauncher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTabLauncher) EXPECT() *MockTabLauncher_Expecter {
	return &MockTabLauncher_Expecter{mock: &_m.Mock}
}

// Launch provides a mock function for the type MockTabLauncher
func (_mock *MockTabLauncher) Launch(context1 context.Context, input zellij.Input) (zellij.Result, error) {
	ret := _mock.Called(context1, input)

	if len(ret) == 0 {
		panic("no return value specified for Launch")
	}

	var r0 zellij.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, zellij.Input) (zellij.Result, error)); ok {
		return returnFunc(context1, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, zellij.Input) zellij.Result); ok {
		r0 = returnFunc(context1, input)
	} else {
		r0 = ret.Get(0).(zellij.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, zellij.Input) error); ok {
		r1 = returnFunc(context1, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTabLauncher_Launch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Launch'
type MockTabLauncher_Launch_Call struct {
	*mock.Call
}

// Launch is a helper method to define mock.On call
//   - context1 context.Context
//   - input zellij.Input
func (_e *MockTabLauncher_Expecter) Launch(context1 interface{}, input interface{}) *MockTabLauncher_Launch_Call {
	return &MockTabLauncher_Launch_Call{Call: _e.mock.On("Launch", context1, input)}
}

func (_c *MockTabLauncher_Launch_Call) Run(run func(context1 context.Context, input zellij.Input)) *MockTabLauncher_Launch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 zellij.Input
		if args[1] != nil {
			arg1 = args[1].(zellij.Input)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTabLauncher_Launch_Call) Return(result zellij.Result, err error) *MockTabLauncher_Launch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockTabLauncher_Launch_Call) RunAndReturn(run func(context1 context.Context, input zellij.Input) (zellij.Result, error)) *MockTabLauncher_Launch_Call {
	_c.Call.Return(run)
	return _c
}
